# src/research_crew/config/tasks.yaml
research_task:
  description: >
    Conduct targeted research to identify major developments related to the Trump administration 
    between June 14th and June 20th, 2025. Focus on:

    1. Official presidential communications (press releases, speeches, verified social media)
    2. Key moments on social media (viral posts, major reactions, trending hashtags involving Trump)
    3. Foreign policy moves (military actions, diplomatic visits, international reactions)
    4. Any federal legislation introduced, passed, or debated that has ties to the Trump platform, allies, or opposition narratives

    Prioritize primary sources, verified media, and timestamps. Present all findings in a structured, chronological format 
    with section headings and source links.

  expected_output: >
    A detailed, well-organized research briefing covering political, legislative, and international events directly 
    connected to the Trump administration within the specified timeframe. Include direct quotes, dates, names, links to sources 
    (articles, tweets, bills), and concise summaries under each section. Format it for easy scanning and downstream use in article writing.

  agent: researcher

analysis_task:
  description: >
    Review the provided research findings and produce a news-style article suitable for a major media outlet. 
    The piece should:

    1. Begin with a strong, engaging lead summarizing the core of the findings.
    2. Present key events or developments in chronological order, with clear transitions.
    3. Offer analysis of how the findings affect U.S. policy, public sentiment, or national interests, using neutral, accessible language.
    4. Reference and hyperlink to original sources where possible for transparency and credibility.
    5. Be formatted like a news article: clear paragraphs, concise sentences, professional tone, and under 500 words.

  expected_output: >
    A newsroom-ready article that combines factual reporting with expert analysis. The final piece should read like it belongs in a major U.S. outlet—informative, sharp, and accessible to a general audience. Include a headline, subhead, and cite all sources with hyperlinks. Keep tone journalistic and avoid academic jargon.

  agent: analyst
  context:
    - research_task
  output_file: output/article.md
