# src/research_crew/config/tasks.yaml (v3)

topic_discovery_task:
  description: >
    Scan for major news and developments related to the Trump administration between 
    June 21st and June 27th, 2025. Focus on legislation, foreign policy, and major social media moments.
    Do NOT conduct deep research. Simply identify less than 10 distinct, high-potential story leads.

  expected_output: >
    A bulleted list of less than 10 concise, one-sentence story leads. Each lead must be a distinct topic.
    Example:
    - A new trade tariff on European cars was announced via a White House press release.
    - Donald Trump made a series of controversial posts on Truth Social regarding the upcoming debate.
    - A key ally in the Senate introduced a new bill related to border security.

  agent: editor
  async_execution: false

# This task is a TEMPLATE. We will create copies of it dynamically.
deep_dive_research_task_template:
  description: >
    For the assigned topic: "{topic}"

    1. Conduct a deep-dive investigation.
    2. Prioritize primary sources: official government websites (whitehouse.gov, congress.gov),
       verified social media accounts, and direct quotes from press briefings.
    3. Find and cite at least 2-3 primary sources.
    4. Compile all findings into a detailed research brief. Include URLs, direct quotes, dates,
       and the names of individuals or organizations involved.
    5. Avoid quoting other news outlets. Quote the original source.

  expected_output: >
    A detailed research brief for the single topic. The brief must be well-structured with clear
    headings, direct source links, and comprehensive summaries. It should serve as the sole source
    of information for a journalist writing an article on this specific topic.

  agent: researcher
  async_execution: true # These can run in parallel

synthesis_task:
  description: >
    Review the collection of detailed research briefs provided from the previous tasks.
    Synthesize them into a single, cohesive news article of 400-600 words.

    Your article must:
    1. Have a compelling headline and a sub-headline.
    2. Start with a strong lead paragraph that summarizes the most important development(s).
    3. Weave the different topics together logically. If they are unrelated, present them as a
       summary of the week's key events.
    4. Maintain a neutral, journalistic tone.
    5. Hyperlink all sources mentioned in the research briefs directly in the article text.

  expected_output: >
    A final, publish-ready news article in Markdown format. The article should be well-written,
    factually accurate, and fully sourced with hyperlinks.

  agent: analyst
  context:
    - topic_discovery_task # This is important to give the analyst context of the original leads
    # The deep dive tasks will be added dynamically
  output_file: output/article.md
  async_execution: false
