# src/research_crew/config/tasks.yaml
research_task:
  description: >
    Find key policies, events, legislation proposed or progressing
    between June 7th, 2025 and June 13th, 2025 with a focus on:
    1. Key events on social media
    2. Presidential statements on official channels
    3. Presidential politics (rallies, fundraisers, polls)
    4. Foreign policy and U.S. intervention
    5. Legislation proposed or voted on in either house of Congress

    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive research document with well-organized sections covering
    all the requested areas aabove. Include specific facts, quotes, figures,
    and social media content where relevant.
  agent: researcher

analysis_task:
  description: >
    Analyze the research findings and create a comprehensive news article.
    Your article should:

    1. Have an executive summary of the findings
    2. Clearly identify all the major events ordered temporaly
    3. Distill the impact of the findings on the United States in a non-partisan manner
    4. Cite sources with direct links where possible.
    5. Be formatted in an easy-to-read, terse manner in less than 500 words.
  expected_output: >
    A polished, professional news article that presents the research
    findings with added analysis and insights. The article should be well-structured
    with an executive summary, key events ordered, cited sources, and expected impact
    on the American public.
  agent: analyst
  context:
    - research_task
  output_file: output/article.md
